//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluations
    {
        public int ID_t { get; set; }
        public int Item_id { get; set; }
        public int Student_id { get; set; }
        public int Yan_e { get; set; }
        public int Fev_e { get; set; }
        public int Mar_e { get; set; }
        public int Apr_e { get; set; }
        public int May_e { get; set; }
        public int Iun_e { get; set; }
        public int Iul_e { get; set; }
        public int Avg_e { get; set; }
        public int Sen_e { get; set; }
        public int Oct_e { get; set; }
        public int Noyab_e { get; set; }
        public int Dec_e { get; set; }
       
        public double SrE => Math.Round(Convert.ToDouble(Yan_e + Fev_e + Mar_e + Apr_e + May_e + Iun_e + Iul_e + Avg_e + Sen_e
            + Oct_e + Noyab_e + Dec_e) / 12, 2);
        public virtual Item Item { get; set; }
        public virtual Student Student { get; set; }
    }
}
