//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Omissions
    {
        public int ID_o { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> Item_id { get; set; }
        public Nullable<int> Size { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Student Student { get; set; }
    }
}
